version: 2.1

executors:
  python-docker-executor:
    docker:
      - image: cimg/base:stable
  java-docker-executor:
    docker:
      - image: chainguard/maven:openjdk-17

jobs:
  build-and-push:
    parameters:
      service:
        type: string
      executor:
        type: string
    executor: "<< parameters.executor >>"
    steps:
      - checkout
      - run:
          name: Install bash if missing
          command: |
            if ! command -v bash >/dev/null 2>&1; then
              echo "Installing bash..."
              apk add --no-cache bash
            else
              echo "bash already available"
            fi
      - run:
          name: Set build path
          command: |
            case "<< parameters.service >>" in
              accounts-db) BUILD_PATH="src/accounts/accounts-db" ;;
              contacts) BUILD_PATH="src/accounts/contacts" ;;
              userservice) BUILD_PATH="src/accounts/userservice" ;;
              frontend) BUILD_PATH="src/frontend" ;;
              balancereader) BUILD_PATH="src/ledger/balancereader" ;;
              ledgerwriter) BUILD_PATH="src/ledger/ledgerwriter" ;;
              transactionhistory) BUILD_PATH="src/ledger/transactionhistory" ;;
              ledger-db) BUILD_PATH="src/ledger/ledger-db" ;;
              loadgenerator) BUILD_PATH="src/loadgenerator" ;;
              *)
                echo "Unknown service: << parameters.service >>"
                exit 1
                ;;
            esac
            echo "export BUILD_PATH=$BUILD_PATH" >> $BASH_ENV

      # Install Skaffold if needed
      - run:
          name: Install Skaffold if needed
          command: |
            case "<< parameters.service >>" in
              accounts-db) BUILD_PATH="src/accounts/accounts-db" ;;
              contacts) BUILD_PATH="src/accounts/contacts" ;;
              userservice) BUILD_PATH="src/accounts/userservice" ;;
              frontend) BUILD_PATH="src/frontend" ;;
              balancereader) BUILD_PATH="src/ledger/balancereader" ;;
              ledgerwriter) BUILD_PATH="src/ledger/ledgerwriter" ;;
              transactionhistory) BUILD_PATH="src/ledger/transactionhistory" ;;
              ledger-db) BUILD_PATH="src/ledger/ledger-db" ;;
              loadgenerator) BUILD_PATH="src/loadgenerator" ;;
              *) echo "Unknown service: << parameters.service >>"; exit 1 ;;
            esac
            echo "Resolved BUILD_PATH=$BUILD_PATH"
            if [ -f "$BUILD_PATH/skaffold.yaml" ]; then
              echo "Installing Skaffold..."
              curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
              chmod +x skaffold
              sudo mv skaffold /usr/local/bin/
            fi

      # Enable Docker builds
      - setup_remote_docker:
          docker_layer_caching: true

      # Build & push Docker image
      - run:
          name: Build and push Docker image
          command: |
            IMAGE_NAME="${DOCKER_REGISTRY}/${DOCKER_ORG}/bank-of-anthos-<< parameters.service >>"
            pwd
            ls -altr
            case "<< parameters.service >>" in
              accounts-db) BUILD_PATH="src/accounts/accounts-db" ;;
              contacts) BUILD_PATH="src/accounts/contacts" ;;
              userservice) BUILD_PATH="src/accounts/userservice" ;;
              frontend) BUILD_PATH="src/frontend" ;;
              balancereader) BUILD_PATH="src/ledger/balancereader" ;;
              ledgerwriter) BUILD_PATH="src/ledger/ledgerwriter" ;;
              transactionhistory) BUILD_PATH="src/ledger/transactionhistory" ;;
              ledger-db) BUILD_PATH="src/ledger/ledger-db" ;;
              loadgenerator) BUILD_PATH="src/loadgenerator" ;;
              *) echo "Unknown service: << parameters.service >>"; exit 1 ;;
            esac
            echo "Resolved BUILD_PATH=$BUILD_PATH"
            echo $BUILD_PATH
            if [ -f "$BUILD_PATH/Dockerfile" ]; then
              echo "Building Dockerfile for << parameters.service >>"
              docker build -t "$IMAGE_NAME:latest" "$BUILD_PATH"
              docker tag "$IMAGE_NAME:latest" "$IMAGE_NAME:${CIRCLE_SHA1}"
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY
              docker push "$IMAGE_NAME:latest"
              docker push "$IMAGE_NAME:${CIRCLE_SHA1}"
            elif [ -f "$BUILD_PATH/skaffold.yaml" ]; then
              echo "Building via Skaffold for << parameters.service >>"
              skaffold build -f "$BUILD_PATH/skaffold.yaml" --default-repo "$DOCKER_REGISTRY/$DOCKER_ORG"
            else
              echo "No Dockerfile or skaffold.yaml found for << parameters.service >>"
              exit 1
            fi

workflows:
  version: 2
  build-and-push-all:
    jobs:
      # Python services
      - build-and-push:
          name: build-python-accounts-db
          service: accounts-db
          executor: python-docker-executor
      - build-and-push:
          name: build-python-contacts
          service: contacts
          executor: python-docker-executor
      - build-and-push:
          name: build-python-userservice
          service: userservice
          executor: python-docker-executor
      - build-and-push:
          name: build-python-frontend
          service: frontend
          executor: python-docker-executor
      - build-and-push:
          name: build-python-ledger-db
          service: ledger-db
          executor: python-docker-executor
      - build-and-push:
          name: build-python-loadgenerator
          service: loadgenerator
          executor: python-docker-executor

      # Java services
      - build-and-push:
          name: build-java-transactionhistory
          service: transactionhistory
          executor: java-docker-executor
      - build-and-push:
          name: build-java-ledgerwriter
          service: ledgerwriter
          executor: java-docker-executor
      - build-and-push:
          name: build-java-balancereader
          service: balancereader
          executor: java-docker-executor
